[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19"
yew-router = "0.16"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"] }
anyhow = "1.0"
wasm-bindgen = "0.2"
common = { path = "../common" }
